jenkins:
  image: andisan/jenkins
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes:
    - ~/jenkins_home:/usr/andisan/Jenkins

seleniumhub:
  image: selenium/hub
  ports:
    - "4444:4444"

firefoxnode:
  image: selenium/node-firefox
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome
  links:
    - seleniumhub:hub
